const colors = require('tailwindcss/colors')

module.exports = {
  content: [],
  tailwindcss: {
    viewer: true,
  },
  theme: {
    fontFamily: {
      sans: ['Gramatika'],
    },
    colors: {
      primary: colors.orange,
      secondary: colors.slate,
      neutral: colors.stone,
      slate: colors.slate,
      info: colors.blue,
      success: colors.emerald,
      warning: colors.amber,
      alert: colors.red,
      black: colors.black,
      white: colors.white,
      yellow: colors.yellow,
      emerald: colors.emerald,
      mint: {
        "50": "#fcfffc",
        "100": "#fcfffc",
        "200": "#e9f5e8",
        "300": "#c8dbc7",
        "400": "#9cb19c",
        "500": "#6d7f6e",
        "600": "#485549",
        "700": "#313b33",
        "800": "#28302b",
        "900": "#233027",
      },
      beige: {
        "50": "hsl(60,27%,98%)",
        "100": "hsl(60,14%,96%)",
        "200": "hsl(20,18%,90%)",
        "300": "hsl(24,17%,83%)",
        "400": "hsl(24,16%,64%)",
        "500": "hsl(25,16%,45%)",
        "600": "hsl(33,16%,32%)",
        "700": "hsl(30,19%,25%)",
        "800": "hsl(12,19%,15%)",
        "900": "hsl(24,29%,10%)",
      },
    },
    extend: {
    },
  },
  plugins: [
    require('tailwind-css-variables')({
      screens: false,
      lineHeight: false,
      letterSpacing: false,
      backgroundSize: false,
      boxShadow: false,
      zIndex: false,
      transitionDuration: 'transition-duration',
      transitionProperty: 'transition-property',
      transitionDelay: 'transition-delay',
      transitionDuration: 'transition-duration',
      transitionTimingFunction: 'transition-timing-function',
      outlineStyle: 'outline-style',
      outlineWidth: 'outline-width',
      outlineOffset: 'outline-offset',
      outlineColor: 'outline-color',
    }),
  ],
  darkMode: 'class',
}
